// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjB5Ak0lrXLfUin2Dk26secDq1IsqpDQk',
    appId: '1:149621142612:web:5bf5a82cf0edb0f4d169c1',
    messagingSenderId: '149621142612',
    projectId: 'blog-b3ca9',
    authDomain: 'blog-b3ca9.firebaseapp.com',
    storageBucket: 'blog-b3ca9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC78ZAMFivlD0ACIbcay3pLxYj3I4EfcaI',
    appId: '1:149621142612:android:2bd491ef4e12a643d169c1',
    messagingSenderId: '149621142612',
    projectId: 'blog-b3ca9',
    storageBucket: 'blog-b3ca9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuj3TU-q5TviTC55zgl2FtEfI3wnnM3iM',
    appId: '1:149621142612:ios:51d5f038f0a4f73cd169c1',
    messagingSenderId: '149621142612',
    projectId: 'blog-b3ca9',
    storageBucket: 'blog-b3ca9.appspot.com',
    iosClientId: '149621142612-l7hsjq9ramehd21m9lpd1ruo0bgb8pp4.apps.googleusercontent.com',
    iosBundleId: 'com.example.blog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuj3TU-q5TviTC55zgl2FtEfI3wnnM3iM',
    appId: '1:149621142612:ios:b3bf349a39b97834d169c1',
    messagingSenderId: '149621142612',
    projectId: 'blog-b3ca9',
    storageBucket: 'blog-b3ca9.appspot.com',
    iosClientId: '149621142612-tiikqi4jr8aijisgeuq1e41lbd202tts.apps.googleusercontent.com',
    iosBundleId: 'com.example.blog.RunnerTests',
  );
}
